# Generated by Django 4.2.4 on 2023-09-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('plan', models.CharField(max_length=200)),
                ('date_aller', models.DateTimeField(auto_now_add=True)),
                ('date_retour', models.DateTimeField(auto_now_add=True)),
                ('sujet_mission', models.TextField()),
                ('accompagnant', models.TextField()),
                ('reponse_admin', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'demande',
            },
        ),
    ]
