# Generated by Django 4.2.4 on 2023-09-07 12:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='date_submit',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='demande',
            name='id_user',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='demande',
            name='date_aller',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='demande',
            name='date_retour',
            field=models.DateTimeField(),
        ),
    ]
