# Generated by Django 4.2.4 on 2023-09-07 12:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField(default=0)),
                ('id_demande', models.IntegerField(default=0)),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('plan', models.CharField(max_length=200)),
                ('date_aller', models.DateTimeField()),
                ('date_retour', models.DateTimeField()),
                ('sujet_mission', models.TextField()),
                ('accompagnant', models.TextField()),
                ('date_submit', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
